FROM ubuntu:20.04

LABEL maintainer="justinas@eofnet.lt"

ENV DEBIAN_FRONTEND=noninteractive
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV PATH="$PATH:/usr/local/go/bin"

RUN ln -fs /usr/share/zoneinfo/Europe/Vilnius /etc/localtime

RUN apt-get update     && \
    apt-get -y upgrade && \
    apt-get install -y --no-install-recommends \
        software-properties-common \
        language-pack-en-base \
        make \
        git \
        zlib1g-dev \
        libssl-dev \
        gperf \
        php-cli \
        cmake \
        g++ \
        prosody \
        wget

RUN git clone https://github.com/tdlib/td.git && cd td && git checkout 8d7bda00a535d1eda684c3c8802e85d69c89a14a  && mkdir -p build

WORKDIR /td/build
RUN cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX:PATH=/usr/local ..
RUN cmake --build . --target install

WORKDIR /
RUN wget https://go.dev/dl/go1.19.10.linux-amd64.tar.gz && \
    tar -C /usr/local -xzf go1.19.10.linux-amd64.tar.gz && \
    export GOPATH=$(go env GOPATH) && \
    git clone https://dev.narayana.im/narayana/telegabber.git && \
    cd telegabber/ && make && cd .. && ls
