version: '3'

services:

  telegabber:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5222:5222
      - 5223:5223
      - 5269:5269
      - 8855:80
    environment:
      TELEGRAM_API_ID: ${API_ID}
      TELEGRAM_API_HASH: ${API_HASH}
      MAIN_HOST: ${MAIN_HOST:-xmpp.lan}
      LINK_HOST: ${LINK_HOST:-media.xmpp.lan}
      FILES_HOST: ${FILES_HOST:-files.xmpp.lan}
      TZ: ${TZ:-Europe/Vilnius}
    volumes:
      - data:/var/lib/prosody
      - sessions:/sessions

volumes:
  data:
  sessions:
